version: "3.6"

networks:
  twitch:

services:
  rabbitmq:
    container_name: twitch-rabbitmq
    image: masstransit/rabbitmq:latest
    networks:
      - twitch
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 10
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"

  quartz:
    container_name: twitch-quartz
    image: masstransit/quartz:latest
    environment:
      MT_Prometheus: 'quartz'
      MT_Scheduler: 'quartz'
      MT_Quartz__ConnectionString: 'Server=tcp:sqlserver;Database=quartznet;Persist Security Info=False;User ID=sa;Password=Quartz!DockerP4ss;Encrypt=False;TrustServerCertificate=True;'
    networks:
      - twitch
    ports:
      - 5002:80

  mongodb:
    container_name: twitch-mongo
    image: mongo:4.2-bionic
    networks:
      - twitch
    ports:
      - 27017-27019:27017-27019

  warehouse:
    image: twitch/warehouse:latest
    container_name: twitch-warehouse
    build:
      context: .
      dockerfile: Dockerfile-Warehouse
    environment:
      - MT_Prometheus=warehouse
      - MT_Scheduler=quartz
    networks:
      - twitch
    ports:
      - 5100:80

  sample:
    image: twitch/sample:latest
    container_name: twitch-sample
    build:
      context: .
      dockerfile: Dockerfile-Sample
    environment:
      - MT_Prometheus=sample
      - MT_Scheduler=quartz
    networks:
      - twitch
    ports:
      - 5200:80