version: "3.6"

networks:
  twitch:

services: 
  rabbitmq:
    container_name: twitch-rabbitmq
    image: masstransit/rabbitmq:latest
    networks:
      - twitch
    ports:
      - "5672:5672"
      - "15672:15672"